language: ruby
cache: bundler
sudo: required
dist: trusty
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - curl -L https://packagecloud.io/michaelmior/coinor/gpgkey | sudo apt-key add -
  - echo "deb https://packagecloud.io/michaelmior/coinor/ubuntu/ precise main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq graphviz
  - sudo apt-get install -qq coinor-libcbc-dev coinor-libcbc3 coinor-libcoinutils-dev coinor-libcoinutils3v5 coinor-libosi-dev coinor-libosi1 coinor-libclp-dev coinor-libclp1 coinor-libcgl-dev coinor-libcgl1 libstdc++6
  - gem install bundler
  - mysql -uroot -e 'create database nose;'
  - mysql -uroot -Dnose < spec/support/data/mysql.sql
  - sudo rm -rf /var/lib/cassandra/*
  - wget https://archive.apache.org/dist/cassandra/3.7/apache-cassandra-3.7-bin.tar.gz && tar -xvzf apache-cassandra-3.7-bin.tar.gz && sudo sh apache-cassandra-3.7/bin/cassandra -R && sleep 15
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - 2.1.10
  # Temoprarily disabled until we get this working since it slows down tests
  # - jruby-9.0.5.0
matrix:
  allow_failures:
    - rvm: jruby-9.0.5.0
script:
  - sed -i '/^--tag/d' .rspec
  - bundle exec rspec
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
  code_climate:
    repo_token: 6bb85eb10136dfdb11e56bf53a9679510ca99c3c0f2495c06d6a3cb9670b9954
services:
  - mongodb
